name: Build and Release CalendarBuddy EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

env:
  EXE_REPO: DaSonOfPoseidon/exeFiles

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt

      - id: extract_version
        shell: pwsh
        run: |
          $text = Get-Content -Raw -Encoding UTF8 calendarbuddy.py
          if ($text -match '(?m)^\s*__version__\s*=\s*["'']([^"'']+)["'']') {
            Write-Output "VERSION=$($matches[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            throw "Version not found in CalendarBuddy.py"
          }

      - name: Build CalendarBuddy executable
        run: pyinstaller CalendarBuddy.spec

      - name: Build Updater executable
        run: pyinstaller updater.spec

      - name: Create and push git tag (if not exists)
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --tags
          TAG="v${{ env.VERSION }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping push"
          else
            git tag -a "$TAG" -m "Release version $TAG"
            git push origin "$TAG"
          fi

      - name: Create or update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: Automated release of CalendarBuddy.exe and updater.exe version v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload CalendarBuddy EXE to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: dist/CalendarBuddy.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Updater EXE to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: dist/updater.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger exeFiles update for CalendarBuddy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ env.EXE_REPO }}
          event-type: exe_update
          client-payload: |
            {
              "exe_name": "CalendarBuddy.exe",
              "version": "${{ env.VERSION }}",
              "release_repo": "CalendarBuddy"
            }

      - name: Trigger exeFiles update for Updater
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ env.EXE_REPO }}
          event-type: exe_update
          client-payload: |
            {
              "exe_name": "updater.exe",
              "version": "${{ env.VERSION }}",
              "release_repo": "CalendarBuddy"
            }
